# Generated by Django 2.0.13 on 2020-06-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='tag',
            new_name='category',
        ),
    ]
