# Generated by Django 2.0.7 on 2020-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200612_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='标题'),
        ),
    ]
