# Generated by Django 2.0.7 on 2020-06-15 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200615_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='pdf',
        ),
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='doc', verbose_name='文件'),
            preserve_default=False,
        ),
    ]
