# Generated by Django 2.0.7 on 2020-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200615_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
    ]
